### ISSUE TITLE
Adjust Java client examples location

### ISSUE THREAD

**Issue by mxsm** [apache/rocketmq-clients#144]
client package example in client dir.  if package jar for client will be packeged example in. can create new module for examples?

**Comment by aaron-ai** [comment]
Thinks for your suggestion, actually we considered about establishing a new module of example, here are the points we concerned:
1. The IDE could not handle the dependency friendly which is shaded in the same project, which may affect the behavior of logback or other dependecies.
2. We must admit that it is better to keep it independent, but is it necessary to release an independent jar for examples, and maybe it is simpler to keep it in the client module? the developer could read the example and check it in real time during the development? I am not sure.
