### ISSUE TITLE
Golang: GenMessageId

### ISSUE THREAD

**Issue by guyinyou** [apache/rocketmq-clients#166]
The messageid generated when sending a message is currently uuid, while the java sdk is generated in MessageIdCodec.getInstance().nextMessageId(). It is recommended to refer to the alignment.

![image](https://user-images.githubusercontent.com/36399867/186084781-d04da324-b2c9-4798-a684-cc9b5131b0ea.png)

**Comment by zzjcool** [comment]
assign to me
