### ISSUE TITLE
Golang: PushConsumer mode

### ISSUE THREAD

**Issue by guyinyou** [apache/rocketmq-clients#169]
Also need to support pushconsumer mode in golang.

The specific design and process are as follows.
[https://github.com/apache/rocketmq-clients/blob/master/docs/workflow.md](url)

**Comment by guyinyou** [comment]
> Also need to support pushconsumer mode in golang.
> 
> The specific design and process are as follows. [https://github.com/apache/rocketmq-clients/blob/master/docs/workflow.md](url)

Refer to the implementation of java will become clearer:
https://github.com/apache/rocketmq-clients/blob/master/java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/PushConsumerImpl.java

**Comment by guyinyou** [comment]
> @guyinyou Hi! The file workflow.md is disappeared. I wonder if it is important as a reference. If so, could you please send a new link ?
The link is correct, but there is a problem with clicking the jump

https://github.com/apache/rocketmq-clients/blob/master/docs/workflow.md

**Comment by AllenZMC** [comment]
Is PushConsumer implemented? @guyinyou
