### ISSUE TITLE
Golang: Make sure 'syncsettings()' succeeds before the client startup

### ISSUE THREAD

**Issue by guyinyou** [apache/rocketmq-clients#180]
Make sure 'syncsettings()' succeeds before the client startup

**Comment by guyinyou** [comment]
done in
https://github.com/apache/rocketmq-clients/pull/161/commits/f9438cbb1fe80671a09ede4fc8a2f485fc0b5fb9

**Comment by Anakin100100** [comment]
@aaron-ai Can we close this issue or is there some work to do here?
