### ISSUE TITLE
Are there plans to support multiple runtimes for rust client?

### ISSUE THREAD

**Issue by iamazy** [apache/rocketmq-clients#228]

**Comment by aaron-ai** [comment]
@lizhanhui PTAL

**Comment by lizhanhui** [comment]
Hi @iamazy Having our library compatible with multiple runtimes is definitely beneficial. But we are still at the very early stage of development. 

The current plan is to target Tokio at first as it is the de facto runtime standard, with a good eco-system and production ready. When we roll out the first release, discuss the outline and steps to make it runtime neutral.
