### ISSUE TITLE
Could MessageView provide a graceful method to get message body

### ISSUE THREAD

**Issue by MumfordSons** [apache/rocketmq-clients#262]
now messageView.getBody()  returns a ByteBuffer object and can't directly get body byte array from ByteBuffer

![196329537-6fc05f7b-de85-4e72-a547-7bddda14e828](https://user-images.githubusercontent.com/45234194/196347996-95eeec2b-ca45-444d-af47-9aed6ff4d3ab.png)

**Comment by aaron-ai** [comment]
The underlying byte array of `bytebuffer` is readonly, which means you could not get it directly, so copy it from `bytebuffer` rather than get it directly if you need `byte[]`. 

```java
byte[] bytes = new byte[body.remaining()];
body.get(bytes);
```

or you could easily get `String` type according to your type.

```java
// Replace by your charset
final String body = StandardCharsets.UTF_8.decode(messageView.getBody()).toString();
```
