### ISSUE TITLE
NPE occurs when the instance username and password are not set

### ISSUE THREAD

**Issue by supercym** [apache/rocketmq-clients#273]
I use 5.0 sdk but refer to how 4.0 is used (like here: https://help.aliyun.com/document_detail/446709.html)

When my instanceUsername and password are both null and I access the Alibaba Cloud MQ instance from vpc, there is an NPE.

![image](https://user-images.githubusercontent.com/25047893/199150885-3ff9f3d8-8305-4be2-a9da-7da23a4db10d.png)

**Comment by aaron-ai** [comment]
Migrate it to [rocketmq](https://github.com/apache/rocketmq).
