### ISSUE TITLE
golang invisibleDuration cause slow consumption for the first time

### ISSUE THREAD

**Issue by yfanswer** [apache/rocketmq-clients#288]
For the first time, need to wait context_deadline, and timeout = invidibleDuration+timeout.

**Comment by aaron-ai** [comment]
is it fixed already? @guyinyou

**Comment by guyinyou** [comment]
If there are messages in the subscribed topic, do it still need to wait for the timeout?

**Comment by yfanswer** [comment]
> If there are messages in the subscribed topic, do it still need to wait for the timeout?

yes

**Comment by guyinyou** [comment]
@aaron-ai let's take a look
