### ISSUE TITLE
Java: Make it possible to control client shutdown in JVM shutdown hook

### ISSUE THREAD

**Issue by lu010610** [apache/rocketmq-clients#291]
ClientImpl‘s Constructor 

```
Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            LOGGER.info("JVM shutdown hook is invoked, clientId={}, state={}", clientId, ClientImpl.this.state());
            ClientImpl.this.stopAsync().awaitTerminated();
        }));
```

Whether this hook can be managed by the user？

Is it possible to delete or add a parameter to control？

**Comment by aaron-ai** [comment]
This hook is provided by JVM, so you could implement your own part.

**Comment by lu010610** [comment]
> This hook is provided by JVM, so you could implement your own part.

Of course I know this hook is provided by JVM.

For example, the sub class ProducerImpl.

In Spring, When JVM received kill signal, this hook will be executed and ProducerImpl will be closed now,  

but I expect that when the spring bean is destroyed, we will invoke the ProducerImpl's close method.

**Comment by lizhanhui** [comment]
> > This hook is provided by JVM, so you could implement your own part.
> 
> Of course I know this hook is provided by JVM.
> 
> For example, the sub class ProducerImpl.
> 
> In Spring, When JVM received kill signal, this hook will be executed and ProducerImpl will be closed now,
> 
> but I expect that when the spring bean is destroyed, we will invoke the ProducerImpl's close method.

@aaron-ai This case makes sense.

**Comment by aaron-ai** [comment]
@lu010610 @lizhanhui got your point.

how about managing the behavior here by providing a switch of enviroment variable/system properties.

**Comment by lu010610** [comment]
> @lu010610 @lizhanhui got your point.
> 
> how about managing the behavior here by providing a switch of enviroment variable/system properties.

that is ok !

**Comment by aaron-ai** [comment]
@lu010610 Could you create a PR to implement this feature? we welcome various contributions!

**Comment by aaron-ai** [comment]
@lu010610 The default implementation of the shutdown hook in the client has been removed already. Thx for your feedback!
