### ISSUE TITLE
php client id cannot be empty

### ISSUE THREAD

**Issue by sundayfly** [apache/rocketmq-clients#308]
vendor/grpc/grpc/src/lib/UnaryCall.php 
echo json_encode($event);die; //lines 65 add

php Producer.php
{"message":"\n\u001f\b\u0478\u0002\u0012\u0019client id cannot be empty","status":{"metadata":[],"code":0,"details":""},"metadata":[]}

client id cannot be empty
Php little information，How to solve it?

**Comment by aaron-ai** [comment]
could you try to put all headers except authorisation? The error message seems could not indicates the real mistake. @bendan365

**Comment by bendan365** [comment]
'update_metadata' => function ($metaData) use ($clientId) {
            $metaData['headers'] = [
                'x-mq-client-id' => $clientId,
                'x-mq-date-time' => '20210309T195445Z',
                'x-mq-request-id' => 'f122a1e0-dbcf-4ca4-9db7-221903354be7',
                'x-mq-language' => 'php',
                'x-mq-client-version' => '5.0.0',
                'x-mq-protocol' => 'v2'
                ]; // Pass the ClientID to the server through the header 
            return $metaData;
        }
        ]);        
response data is 
{"message":"\n\u001f\b\u0478\u0002\u0012\u0019client id cannot be empty","status":{"metadata":[],"code":0,"details":""},"metadata":[]}

**Comment by aaron-ai** [comment]
@drpmma PTAL

**Comment by aaron-ai** [comment]
I can not reproduce this problem in java client, but we will track this problem.

**Comment by aaron-ai** [comment]
> 'update_metadata' => function ($metaData) use ($clientId) { $metaData['headers'] = [ 'x-mq-client-id' => $clientId, 'x-mq-date-time' => '20210309T195445Z', 'x-mq-request-id' => 'f122a1e0-dbcf-4ca4-9db7-221903354be7', 'x-mq-language' => 'php', 'x-mq-client-version' => '5.0.0', 'x-mq-protocol' => 'v2' ]; // Pass the ClientID to the server through the header return $metaData; } ]); response data is {"message":"\n\u001f\b\u0478\u0002\u0012\u0019client id cannot be empty","status":{"metadata":[],"code":0,"details":""},"metadata":[]}


@sundayfly @bendan365 You should not set `headers` in `metaData`, and put all headers into it.

example:
```php
$metaData['x-mq-client-id'] = [$clientId];
```

**Comment by bendan365** [comment]
thanks,but the response data is 
object(stdClass)#772 (3) {
  ["message"]=>
  string(180) "
��OK'
xlp_test_topic"
broker-a*)
xlp_test_topic"
broker-a*)
xlp_test_topic"
broker-a*)
xlp_test_topic"
broker-a*"
  ["status"]=>
  object(stdClass)#1230 (3) {
    ["metadata"]=>
    array(0) {
    }
    ["code"]=>
    int(0)
    ["details"]=>
    string(0) ""
  }
  ["metadata"]=>
  array(0) {
  }
}

**Comment by aaron-ai** [comment]
@bendan365 I am not familar with PHP, but the expected response had been returned according to your response.
