### ISSUE TITLE
ReceiveMessage and the response is "null. NullPointerException. org.apache.rocketmq.proxy.grpc.v2.consumer.ReceiveMessageActivity.receiveMessage(ReceiveMessageActivity.java:65)"

### ISSUE THREAD

**Issue by bendan365** [apache/rocketmq-clients#315]
{
    "status": {
        "code": "INTERNAL_SERVER_ERROR",
        "message": "null. NullPointerException. org.apache.rocketmq.proxy.grpc.v2.consumer.ReceiveMessageActivity.receiveMessage(ReceiveMessageActivity.java:65)"
    }
}

**Comment by colprog** [comment]
I recent fixed a similar bug in dotnet driver. for the dotnet driver, the problem is missing periodic heartbeat. so after a while, client session is recycled on the proxy, giving this exact error.

**Comment by JanYork** [comment]
Is this problem solved? I also encountered this problem, can you tell me how you solved it?
