### ISSUE TITLE
simpleconsumer in C# examples  dosen‘t work

### ISSUE THREAD

**Issue by fakerpawnno1** [apache/rocketmq-clients#322]
when I buy aliyun rocketmq5.0 instance and create topic and consumer group ， replace examples file with them。simpleconsumer occurs dosen‘t work。  but when i use it alone，it works。

**Comment by aaron-ai** [comment]
What do you mean "use it alone"?

**Comment by fakerpawnno1** [comment]
> What do you mean "use it alone"?

just comment send delay and fifo messages in main method

**Comment by lizhanhui** [comment]
> > What do you mean "use it alone"?
> 
> just comment send delay and fifo messages in main method

@fakerpawnno1 Sorry, but I still cannot get your point, can you paste the code that does not work?
