### ISSUE TITLE
请问，这个版本的 java 客户端和 rocketmq-client 有什么区别？

### ISSUE THREAD

**Issue by ifeisier** [apache/rocketmq-clients#325]
和下面这个客户端有什么区别

```xml
<dependency>
    <groupId>org.apache.rocketmq</groupId>
    <artifactId>rocketmq-client</artifactId>
    <version>5.0.0</version>
</dependency>
```

**Comment by aaron-ai** [comment]
`rocketmq-client-java` 对应的客户端是 RocketMQ 社区推荐的新的 5.0 客户端，未来客户端新的 feature 和主力维护方向是在当前仓库进行的（包含以此衍生的所有多语言客户端），关于这一点，你可以在 [RocketMQ 官网](https://rocketmq.apache.org/)进行参阅。

`rocketmq-client` 对应的是 RocketMQ 旧有的客户端，沿袭 RocketMQ 的旧有设计和编码，原则上只做 bugfix，不再进行 feature 新增。
