### ISSUE TITLE
新版本client代码里面如何创建topic

### ISSUE THREAD

**Issue by alicgq** [apache/rocketmq-clients#333]
找了半天没找到，mqadmin这些全部变成空的了，dashboard只能创建normal topic

**Comment by aaron-ai** [comment]
@alicgq ，在新版本客户端中，你仍然可以使用 mqadmin 来创建 topic，目前运维侧的功能并不包含在客户端中。

**Comment by alicgq** [comment]
@aaron-ai 新版本没有相应的方法；

**Comment by aaron-ai** [comment]
> @aaron-ai 新版本没有相应的方法；

还是使用 rocketmq 主仓库中的 mqadmin 工具来进行创建的。
