### ISSUE TITLE
Rust: maybe change `slog` to `tracing`? 

### ISSUE THREAD

**Issue by CherishCai** [apache/rocketmq-clients#334]
https://crates.io/crates/tracing

`tracing` with `tracing-opentelemetry` or else.

**Comment by lizhanhui** [comment]
@CherishCai Yes. It is still at a very early stage of development. Things are open to change as long as it makes sense.

**Comment by CherishCai** [comment]
@lizhanhui 同学组织下 Rust 客户端的开发嘛，我这边可以领一些任务

**Comment by CherishCai** [comment]
发现这个仓库：https://github.com/messense/rocketmq-rs
也很久没维护了，它占用了 crates `rocketmq` ，或者可以邀请维护者参与到官方仓库开发

**Comment by aaron-ai** [comment]
@CherishCai 感谢你的关注，为了让社区的同学可以更快速熟悉和参与贡献，我们最近会发布一些任务和具体步骤。你可以先参照其他语言比较成熟的版本先熟悉一下，如果有任何建议和想法，也欢迎随时反馈。

对 [rocketmq-rs](https://github.com/messense/rocketmq-rs) 这个 repo 的建议，我认为是非常有意义的，我们也会尝试联系对应的开发者。

**Comment by lizhanhui** [comment]
> 发现这个仓库：https://github.com/messense/rocketmq-rs 也很久没维护了，它占用了 crates `rocketmq` ，或者可以邀请维护者参与到官方仓库开发

This is not an issue. The repository author, `messense`, is willing to transfer the crate as long as there is a need.

**Comment by lizhanhui** [comment]
> @lizhanhui 同学组织下 Rust 客户端的开发嘛，我这边可以领一些任务

I am currently sketching the modular design with very limited bandwidth. Once the design is completed, I would create a bunch of task issues.

**Comment by messense** [comment]
Hi, happy to transfer the `rocketmq` crate to `rocketmq-clients` maintainers, @aaron-ai doesn't have a crates.io account so I can't transfer it now.

**Comment by aaron-ai** [comment]
> Hi, happy to transfer the `rocketmq` crate to `rocketmq-clients` maintainers, @aaron-ai doesn't have a crates.io account so I can't transfer it now.

@messense Sorry, I created crates.io account just now. Could you transfer it to me now?

**Comment by messense** [comment]
Done.

**Comment by CherishCai** [comment]
另外可以学习借鉴 https://github.com/streamnative/pulsar-rs
