### ISSUE TITLE
will this client implements the old  ConsumeMessageTraceHookImpl based on new MessageInterceptor

### ISSUE THREAD

**Issue by leizhiyuan** [apache/rocketmq-clients#345]
now , It seems we do not setup the tracer hook in this new client.

is any plan for this, or will provide another way to process the msg trace?

**Comment by aaron-ai** [comment]
[Here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/rocketmq/rocketmq-client/rocketmq-client-5.0) is the implementation of the client trace you could refer to, message trace in RocketMQ 5.0 will by managed by OpenTelemetry.

**Comment by leizhiyuan** [comment]
thanks for your reply , so it means rocketmq 5 will not provide the old way(use the RMQ_SYS_TRACE_TOPIC to store and query)

users should deploy a new collector (or buy some cloud native service) to show the trace data collected by OpenTelemetry

or they should implement the ConsumeMessageTraceHookImpl themself.
