### ISSUE TITLE
Allow user to disable TLS

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq-clients#355]

**Comment by lizhanhui** [comment]
Why h2c now that a lot of potential issues are out there? Note [virtually all browsers supporting HTTP/2 requires TLS](https://stackoverflow.com/questions/34076231/why-do-browser-implementations-of-http-2-require-tls), grpc-go needs extra tuning to work: https://github.com/grpc/grpc-go/issues/555

A second issue is, are you planning to align all bindings on this?

**Comment by aaron-ai** [comment]
Since gRPC TLS doesn't work out-of-box, this issue aims to provide another option to quick start.
