### ISSUE TITLE
Question ：GolangSDK create grpc conn failed

### ISSUE THREAD

**Issue by zymaozZ** [apache/rocketmq-clients#357]
I just copied code from 

> example/producer/normal/main.go

and then update const variables.

But always get error like this

![image](https://user-images.githubusercontent.com/18400600/217976668-406178d1-b00f-4ccc-a8a3-3777ae80fd2a.png)

Anyone knows waht can I do? I have confused about  it for almost three weeks ...

code:
```
package main

import (
	"context"
	"fmt"
	rmq_client "github.com/apache/rocketmq-clients/golang"
	"github.com/apache/rocketmq-clients/golang/credentials"
	"log"
	"os"
	"strconv"
	"time"
)

const (
	Topic     = "TestTopic"
	Endpoint  = "ip:port"
	AccessKey = "AccessKey"
	SecretKey = "SecretKey"
)

func main() {
	os.Setenv("mq.consoleAppender.enabled", "true")
	os.Setenv(rmq_client.CLIENT_LOG_LEVEL, "error")
	rmq_client.ResetLogger()
	// new producer instance
	producer, err := rmq_client.NewProducer(&rmq_client.Config{
		Endpoint: Endpoint,
		Credentials: &credentials.SessionCredentials{
			AccessKey:    AccessKey,
			AccessSecret: SecretKey,
		},
	},
		rmq_client.WithTopics(Topic),
	)
	if err != nil {
		log.Fatal(err)
	}
	// start producer
	err = producer.Start()
	if err != nil {
		log.Fatal(err)
	}
	// gracefule stop producer
	defer producer.GracefulStop()

	for i := 0; i < 10; i++ {
		// new a message
		msg := &rmq_client.Message{
			Topic: Topic,
			Body:  []byte("this is a message : " + strconv.Itoa(i)),
		}
		// set keys and tag
		msg.SetKeys("a", "b")
		msg.SetTag("ab")
		// send message in sync
		resp, err := producer.Send(context.TODO(), msg)
		if err != nil {
			log.Fatal(err)
		}
		for i := 0; i < len(resp); i++ {
			fmt.Printf("%#v\n", resp[i])
		}
		// wait a moment
		time.Sleep(time.Second * 1)
	}
}

```

**Comment by zymaozZ** [comment]
> Could you please use the `go get -u github.com/apache/rocketmq-clients/golang` to update to latest version and try again?


Thanks for reply.But I have updated the latest version and used code in ` examples/producer/normal `, and still get the same error info. 
![image](https://user-images.githubusercontent.com/18400600/218611464-d2943a29-9c6e-47de-b3db-9ec97aaa6e67.png)

Is there any configurations or dependencies I should check again?

**Comment by s5s-TMD** [comment]
grpc default endPoint is localhost:8081

**Comment by s5s-TMD** [comment]
> grpc default endPoint is localhost:8081



> > Could you please use the `go get -u github.com/apache/rocketmq-clients/golang` to update to latest version and try again?
> 
> Thanks for reply.But I have updated the latest version and used code in `examples/producer/normal`, and still get the same error info. ![image](https://user-images.githubusercontent.com/18400600/218611464-d2943a29-9c6e-47de-b3db-9ec97aaa6e67.png)
> 
> Is there any configurations or dependencies I should check again?


grpc default endPoint is localhost:8081, pay attention to port

**Comment by zymaozZ** [comment]
> 

The 8081 port is not in use

**Comment by zymaozZ** [comment]
If you start broker with "--enable-proxy", then you should specify the "endpoint" parameter to "locaohost:8081" or "127.0.0.1:8081"

**Comment by kingdom998** [comment]
不能使用 9876 如果 使用 docker-compose 启动的时候，设置的对外的代理窗口要为 8081
样例如下：
`
version: '3.8'
services:
  namesrv:
    image: apache/rocketmq:5.1.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    networks:
      - rocketmq
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:5.1.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on:
      - namesrv
    networks:
      - rocketmq
    command: sh mqbroker
  proxy:
    image: apache/rocketmq:5.1.0
    container_name: rmqproxy
    networks:
      - rocketmq
    depends_on:
      - broker
      - namesrv
    ports:
      - 18080:8080
      - 8081:8081
    restart: on-failure
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    command: sh mqproxy
  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    ports:
      - 8888:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv:9876
    depends_on:
      - namesrv
    networks:
      - rocketmq
networks:
  rocketmq:
    driver: bridge
`
