### ISSUE TITLE
java:顺序消费问题。4.0版本中可以通过MessageListenerOrderly控制严格顺序消费，5.0sdk中有类似的解决方案么。

### ISSUE THREAD

**Issue by howeycheng** [apache/rocketmq-clients#373]

**Comment by aaron-ai** [comment]
you can use -o option of `mqadmin updateSubGroup` to set FIFO consumption for group.

![image](https://user-images.githubusercontent.com/19537356/222358197-a4161802-d17b-4ea0-b7d4-bb61eb7bb466.png)

**Comment by aaron-ai** [comment]
@howeycheng FIFO consumer group keeps the same semantics with `MessageListenerOrderly` with RocketMQ 4.0.

**Comment by howeycheng** [comment]
thanks！
