### ISSUE TITLE
Golang: 客户端不支持连接RocketMQ5集群

### ISSUE THREAD

**Issue by Richelieu42** [apache/rocketmq-clients#377]
尝试在Consumer实例执行Start()前通过reflect修改其内部的Address，但没用。
PS：查了下Java客户端依赖，是支持通过“;”连接RocketMQ5集群的。

**Comment by aaron-ai** [comment]
可以更加详细描述一下问题吗？`;` 是指有多个 RocketMQ 接入点？

**Comment by Richelieu42** [comment]
是的，有多个 RocketMQ 接入点。
（1）使用Java依赖，可以连接RocketMQ5集群（多个接入点）。
![image](https://user-images.githubusercontent.com/115224697/222364971-e0155ddc-49b6-4488-b664-10da42a7c299.png)
（2）使用Golang依赖，则无法连接RocketMQ5集群（多个接入点），查了下源码，并没有对“;”进行处理。
![image](https://user-images.githubusercontent.com/115224697/222365347-aa4bdf84-ce97-45cc-9b40-f74b36f95862.png)

官方是否有Golang连接RocketMQ5集群（多个接入点）的demo，有的话能否提供下？

**Comment by francisoliverlee** [comment]
这个确实一个bug， golang把传入的target当作一个地址处理的。感兴趣的话， 老哥可以提个PR修复下

**Comment by imp2002** [comment]
I am interested in it, could you assign it to me? @aaron-ai

**Comment by francisoliverlee** [comment]
> @francisoliverlee Could you describe the issue in English? I'd be happy to solve it but I don't really get the core of the problem from the Google Translate translation.

 golang client does support more than one namesrv. rocketmq's namesrvs should be combine like "127.0.0.1:9876;127.0.0.2:9876", but golang sdk does not split namesrvs with ";" 

https://user-images.githubusercontent.com/115224697/222365347-aa4bdf84-ce97-45cc-9b40-f74b36f95862.png
