### ISSUE TITLE
请问c#客户端支持通过name server连接吗？

### ISSUE THREAD

**Issue by anchurcn** [apache/rocketmq-clients#422]

**Comment by aaron-ai** [comment]
仅支持使用 gRPC proxy 接入。

**Comment by anchurcn** [comment]
@aaron-ai 感谢你的回复。那么我想通过 nameserver 连接 rocketmq，请问有什么 .net 的 rocketmq 客户端支持，且支持顺序消息？

**Comment by aaron-ai** [comment]
> 

目前没有官方 C# SDK 支持 nameserver 接入，未来也不会支持。

**Comment by anchurcn** [comment]
@aaron-ai 了解。grpc proxy 的连接方式能替代 nameserver 的连接方式吗？我目前没有比较深入了解这两个连接方式的区别。

**Comment by aaron-ai** [comment]
> @aaron-ai 了解。grpc proxy 的连接方式能替代 nameserver 的连接方式吗？我目前没有比较深入了解这两个连接方式的区别。

协议上完全可以代替的，目前 C# 使用的是新的 simple consumer 来接入的，对于客户端上一些没有对齐的 feature，我们也会陆续补齐。

**Comment by anchurcn** [comment]
@aaron-ai 明白了

**Comment by anchurcn** [comment]
@aaron-ai 你好，这样看起来只支持连接 RocketMQ 5.0 是吧？RocketMQ 4.9 我看是没有 proxy 这个组件的。
