### ISSUE TITLE
golang can't set properties

### ISSUE THREAD

**Issue by vertee** [apache/rocketmq-clients#427]
the version of golang  can't set properties in message

**Comment by francisoliverlee** [comment]
try this:
```golang
msg.GetProperties()["key"] = "value"
```
![image](https://user-images.githubusercontent.com/5908412/228714347-9bf9f38e-a5f9-4464-8808-d5e12a475cba.png)

**Comment by guyinyou** [comment]
> the version of golang can't set properties in message

https://github.com/apache/rocketmq-clients/pull/432
