### ISSUE TITLE
Enhance Rust SDK CI Pipeline

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq-clients#459]
Jon is a very professional and popular Rust developer... We should reuse pipelines shared: https://github.com/jonhoo/rust-ci-conf

**Comment by lizhanhui** [comment]
@ShadowySpirits Would you like to take a look?

**Comment by ShadowySpirits** [comment]
> @ShadowySpirits Would you like to take a look?

Sure, please assign it to me.

**Comment by ShadowySpirits** [comment]
I have added test coverage ci for rust SDK #489
