### ISSUE TITLE
golang clinet does not implement ForwardMessageToDeadLetterQueue

### ISSUE THREAD

**Issue by Samuel-Solis-g** [apache/rocketmq-clients#468]
Why doesn't golang implement ForwardMessageToDeadLetterQueue, is there any other way to implement early end retry on the client side and put the message into DLQ?

**Comment by aaron-ai** [comment]
@Samuel-Solis-g Thank you for your interest. Please note that `ForwardMessageToDeadLetterQueue` is not a generic RPC request for consumers and is only relevant for PushConsumers.

Currently, there is no corresponding implementation of PushConsumer in the Go language, but some developers are working on it. It would be great if you could also be involved. see #463
