### ISSUE TITLE
 err=create grpc conn failed, err=context deadline exceeded

### ISSUE THREAD

**Issue by mirror6Y** [apache/rocketmq-clients#492]
Normal message demo exception running example

**Comment by diwangtseb** [comment]
@mirror6Y golangsdk?You're probably connecting to localhost:9876? try connect proxy port 8080

**Comment by mirror6Y** [comment]
get . thanks

**Comment by willis-yang** [comment]
> @mirror6Y golangsdk?You're probably connecting to localhost:9876? try connect proxy port 8080

i have confusion  why using 8080 port ? nameserver is 9876?

**Comment by lizhanhui** [comment]
> > @mirror6Y golangsdk?You're probably connecting to localhost:9876? try connect proxy port 8080
> 
> i have confusion why using 8080 port ? nameserver is 9876?

Clients in this repository speak specific dialects of HTTP 2,  named as gRPC and the HTTP 2 server, similar to what Nginx does, are acting as a reverse proxy of classic RocketMQ cluster.

SDK 5.x --> proxy --> brokers. Name servers can be thought as look-aside routing service, guiding proxy where the broker nodes are and how messages/queues are placed.

**Comment by willis-yang** [comment]
> > > @mirror6Y golangsdk?You're probably connecting to localhost:9876? try connect proxy port 8080
> > 
> > 
> > i have confusion why using 8080 port ? nameserver is 9876?
> 
> Clients in this repository speak specific dialects of HTTP 2, named as gRPC and the HTTP 2 server, similar to what Nginx does, are acting as a reverse proxy of classic RocketMQ cluster.
> 
> SDK 5.x --> proxy --> brokers. Name servers can be thought as look-aside routing service, guiding proxy where the broker nodes are and how messages/queues are placed.

get,thx

**Comment by carlye** [comment]
注意：这里连接mqproxy的时候，需要注意。如果使用docker或者docker-compose映射的端口，导致容器内和容器外端口不一致的时候，也会失败！！！。需要在配置文件中指定端口号，和宿主机开发端口一致！！。"grpcServerPort": 10081
