### ISSUE TITLE
[Bug] rocketmq-clients for golang How to add custom attributes

### ISSUE THREAD

**Issue by thousmile** [apache/rocketmq-clients#574]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

Go

### Runtime Platform Environment

go version go1.20.6 windows/amd64

### RocketMQ Version of the Client/Server

github.com/apache/rocketmq-clients/golang/v5 v5.0.1-rc.4

### Run or Compiler Version

1

### Describe the Bug

rocketmq message How to add custom key-value pair attributes 

### Steps to Reproduce

1

### What Did You Expect to See?

1

### What Did You See Instead?

1

### Additional Context

```golang
package main

import (
	"encoding/binary"
	"encoding/json"
	"fmt"
	rmq_client "github.com/apache/rocketmq-clients/golang/v5"
	"testing"
)

func TestRocketmqMsg(t *testing.T) {
	message := rmq_client.Message{
		Topic: "hello",
		Body:  []byte("this is a message : "),
		Tag:   nil,
	}
}

```

message  How to add custom key-value pair attributes

For example: Headers in sarama kafka

```
	message := &sarama.ProducerMessage{
		Topic: "hello",
		Value: sarama.StringEncoder("this is a message : "),
		Headers: []sarama.RecordHeader{
			{Key: []byte("tenantId"), Value: []byte("1654qwe")},
			{Key: []byte("areaId"), Value: bytes},
		},
	}
```

**Comment by francisoliverlee** [comment]
this demo work with me
broker : V5_1_3
client: master updated at 2023-06-19
```
func main() {
	os.Setenv("mq.consoleAppender.enabled", "true")
	rmq_client.ResetLogger()
	// In most case, you don't need to create many producers, singleton pattern is more recommended.
	producer, err := rmq_client.NewProducer(&rmq_client.Config{
		Endpoint: Endpoint,
		Credentials: &credentials.SessionCredentials{
			AccessKey:    AccessKey,
			AccessSecret: SecretKey,
		},
	},
		rmq_client.WithTopics(Topic),
	)
	if err != nil {
		log.Fatal(err)
	}
	// start producer
	err = producer.Start()
	if err != nil {
		log.Fatal(err)
	}
	// graceful stop producer
	defer producer.GracefulStop()

	for i := 0; i < 10; i++ {
		// new a message
		msg := &rmq_client.Message{
			Topic: Topic,
			Body:  []byte("this is a message : " + strconv.Itoa(i)),
		}
		// set keys and tag
		msg.SetKeys("a", "b")
		msg.SetTag("ab")
		msg.AddProperty("k1", "v1")
		msg.AddProperty("k2", "v2")
		msg.AddProperty("k3", "v3")
		// send message in sync
		resp, err := producer.Send(context.TODO(), msg)
		if err != nil {
			log.Fatal(err)
		}
		for i := 0; i < len(resp); i++ {
			fmt.Printf("%#v\n", resp[i])
		}
		// wait a moment
		time.Sleep(time.Second * 1)
	}
}
```
![image](https://github.com/apache/rocketmq-clients/assets/5908412/37cf6279-3cd4-4665-94d1-6797428bbb67)

**Comment by thousmile** [comment]
@francisoliverlee ok！Thanks！
