### ISSUE TITLE
[Bug] Rust client Failed to parse config at client.handle_telemetry_command 

### ISSUE THREAD

**Issue by doveq** [apache/rocketmq-clients#598]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

Rust

### Runtime Platform Environment

OS: Ubuntu 22.04

### RocketMQ Version of the Client/Server

Client Version: 5.0.0
Server Version: 5.1.3

### Run or Compiler Version

rustc (1.66.1+dfsg0ubuntu1-0ubuntu0.22.04.1)

### Describe the Bug

Sep 07 07:33:13.828 ERRO[/home/waa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rocketmq-5.0.0/src/client.rs:196:33] handle telemetry command failed: Failed to parse config at client.handle_telemetry_command => receive telemetry command but there is no handler

Context:
    command: Settings(Settings { client_type: Some(Producer), access_point: None, backoff_policy: Some(RetryPolicy { max_attempts: 3, strategy: Some(ExponentialBackoff(ExponentialBackoff { initial: Some(Duration { seconds: 0, nanos: 10000000 }), max: Some(Duration { seconds: 1, nanos: 0 }), multiplier: 2.0 })) }), request_timeout: Some(Duration { seconds: 3, nanos: 0 }), user_agent: Some(Ua { language: Rust, version: "5.0.0", platform: "Ubuntu 22.04", hostname: "test1" }), metric: Some(Metric { on: false, endpoints: None }), pub_sub: Some(Publishing(Publishing { topics: [Resource { resource_namespace: "", name: "test123" }], max_body_size: 4194304, validate_message_type: true })) })
, component: client

### Steps to Reproduce

执行官方案例测试发送消息。  https://github.com/apache/rocketmq-clients/blob/master/rust/examples/producer.rs 

### What Did You Expect to See?

无

### What Did You See Instead?

无

**Comment by ShadowySpirits** [comment]
Currently, the Rust Client does not handle the Settings command from the Proxy as it is still a work-in-progress. Please feel free to submit a PR to implement it.
