### ISSUE TITLE
[Bug] topicsOfInterest should pass a reference instead of a value

### ISSUE THREAD

**Issue by forgivemyheart** [apache/rocketmq-clients#639]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

C++

### Runtime Platform Environment

all

### RocketMQ Version of the Client/Server

all 

### Describe the Bug

void SimpleConsumerImpl::topicsOfInterest(std::vector<std::string> topics) {
  absl::MutexLock lk(&subscriptions_mtx_);
  for (const auto& entry : subscriptions_) {
    if (std::find(topics.begin(), topics.end(), entry.first) == topics.end()) {
      topics.push_back(entry.first);
    }
  }
}

Based on the topicsOfInterest function's intention, which is to modify the input parameter, it should pass a reference instead of a value.

### Steps to Reproduce

code error

### What Did You Expect to See?

Input parameters are modified correctly

### What Did You See Instead?

The input parameters have not been modified

**Comment by lizhanhui** [comment]
This method is abused. It carries two different semantics in different places and we need to fix it. You are welcome to create a pull request.

**Comment by forgivemyheart** [comment]
It seems that it was correct before the modification .Support client metric exporting (https://github.com/apache/rocketmq-clients/pull/39)，it's simi

**Comment by forgivemyheart** [comment]
It seems that it was correct before the modification .Support client metric exporting (https://github.com/apache/rocketmq-clients/pull/39)

**Comment by lizhanhui** [comment]
> It seems that it was correct before the modification .Support client metric exporting (#39)

Right...That is when a second use case was introduced and things are messed up. If you have interest, you may create a pull request to get things fixed and I am glad to review and have it rectified.

**Comment by lizhanhui** [comment]
@forgivemyheart I've created a pull request, you may have a review if you like
