### ISSUE TITLE
[Bug] nodejs 使用 mq consumer 时连接时间一长就出现断连

### ISSUE THREAD

**Issue by moling1234** [apache/rocketmq-clients#649]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

Node.js

### Runtime Platform Environment

macOS 14.0 23A344

### RocketMQ Version of the Client/Server

rocketmq-client-nodejs@1.0.0-beta.1

### Run or Compiler Version

node@20.10.0

### Describe the Bug

nodejs 使用 mq consumer 时连接时间一长就出现断连
<img width="1088" alt="image" src="https://github.com/apache/rocketmq-clients/assets/32126933/aac12769-adf7-480e-9fa3-7af92a880453">

InternalErrorException: [request-id=undefined, response-code=50001] INTERNAL_SERVER_ERROR
    at Function.check (/Users/node_modules/rocketmq-client-nodejs/src/exception/StatusChecker.ts:81:15)
    at SimpleConsumer.receiveMessage (/Users/node_modules/rocketmq-client-nodejs/src/consumer/Consumer.ts:78:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SimpleConsumer.receive (/Users/node_modules/rocketmq-client-nodejs/src/consumer/SimpleConsumer.ts:122:12)
    at /Users/inform-mq/inform-mq.service.ts:109:30 {
  code: 50001

### Steps to Reproduce

长时间使用 consumer 连接

### What Did You Expect to See?

长时间使用 consumer 连接不断连

### What Did You See Instead?

长时间使用 consumer 连接断连

**Comment by moling1234** [comment]
Who can help me solve this bug?

**Comment by moling1234** [comment]
@ShadowySpirits help me

**Comment by luozhuxi1** [comment]
> ### Before Creating the Bug Report
> * [x]  I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).
> * [x]  I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.
> * [x]  I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.
> 
> ### Programming Language of the Client
> Node.js
> 
> ### Runtime Platform Environment
> macOS 14.0 23A344
> 
> ### RocketMQ Version of the Client/Server
> rocketmq-client-nodejs@1.0.0-beta.1
> 
> ### Run or Compiler Version
> node@20.10.0
> 
> ### Describe the Bug
> nodejs 使用 mq consumer 时连接时间一长就出现断连 <img alt="image" width="1088" src="https://private-user-images.githubusercontent.com/32126933/289071848-aac12769-adf7-480e-9fa3-7af92a880453.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NzUyNTgsIm5iZiI6MTcxMzU3NDk1OCwicGF0aCI6Ii8zMjEyNjkzMy8yODkwNzE4NDgtYWFjMTI3NjktYWRmNy00ODBlLTlmYTMtN2FmOTJhODgwNDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDAxMDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxOGRlNmEzYjVkZThkNGU1OTFiMGJjZGM5ZWI4NDQ0NmJmNDk2MDk0YTg5ZTQ5OTcxMzY0NDQ5YTM3NGY3NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2KrcmRs80WtvKj17Dw57iYwHyJ0mI2rXqKGHErOhcs8">
> 
> InternalErrorException: [request-id=undefined, response-code=50001] INTERNAL_SERVER_ERROR at Function.check (/Users/node_modules/rocketmq-client-nodejs/src/exception/StatusChecker.ts:81:15) at SimpleConsumer.receiveMessage (/Users/node_modules/rocketmq-client-nodejs/src/consumer/Consumer.ts:78:19) at processTicksAndRejections (node:internal/process/task_queues:95:5) at SimpleConsumer.receive (/Users/node_modules/rocketmq-client-nodejs/src/consumer/SimpleConsumer.ts:122:12) at /Users/inform-mq/inform-mq.service.ts:109:30 { code: 50001
> 
> ### Steps to Reproduce
> 长时间使用 consumer 连接
> 
> ### What Did You Expect to See?
> 长时间使用 consumer 连接不断连
> 
> ### What Did You See Instead?
> 长时间使用 consumer 连接断连
> 
> ### Additional Context
> _No response_
请求这个解决了吗

**Comment by moling1234** [comment]
@luozhuxi1 没有，我自己处理了一下自动重连，但是这个自动重连会有延迟

**Comment by black0207** [comment]
这个问题如何解决，不断重连会导致服务器性能问题，能解决这个问题吗
