### ISSUE TITLE
[Bug] golang 版本无法连接到本地启动的rocketmq

### ISSUE THREAD

**Issue by zkcrescent** [apache/rocketmq-clients#650]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

Go

### Runtime Platform Environment

Macos with docker

### RocketMQ Version of the Client/Server

server 5.1.4 client v5.0.1-rc.5

### Describe the Bug

docker 启动了namesrv + broker + dashboard 并暴漏了相关端口
![image](https://github.com/apache/rocketmq-clients/assets/14883259/15e26f8e-3982-48b9-b1ed-8572913a7859)
从 网页上访问 127.0.0.1:8080 可以正常配置topic 并创建了test topic
![image](https://github.com/apache/rocketmq-clients/assets/14883259/2bb5bed1-1592-4e6e-a123-8ade6d1e24c2)
broker 配置如下
![image](https://github.com/apache/rocketmq-clients/assets/14883259/6f6f3105-1ce9-4dc8-a85e-041fc5f8cb06)

使用了example 中的生产者用例代码，修改 topic, accesskey 等参数
![image](https://github.com/apache/rocketmq-clients/assets/14883259/3d9fcefd-01b8-4c6e-92a7-a28a20bce49c)
报错
![image](https://github.com/apache/rocketmq-clients/assets/14883259/28e8a132-9974-40c6-b92a-61459e1f83c8)

### Steps to Reproduce

参考上文

### What Did You Expect to See?

期望正常链接

### What Did You See Instead?

链接超时

**Comment by lollipopjin** [comment]
看着是你的5.1.4的Server在部署的时候开启了Proxy代理模式，If so，你需要用到grpc的客户端来连接，参考：https://github.com/apache/rocketmq-clients 这个开源库

**Comment by zkcrescent** [comment]
我的代码就是用的上面这个仓库的 https://github.com/apache/rocketmq-clients/blob/master/golang/example/producer/async/main.go

**Comment by lollipopjin** [comment]
> 我的代码就是用的上面这个仓库的 https://github.com/apache/rocketmq-clients/blob/master/golang/example/producer/async/main.go

抱歉上面看岔了，那现在的状态是你依赖的这个客户端是grpc协议的，但你部署的broker不支持这个协议；

修正方式：
方式 1） 用remoting协议的go客户端去连；https://github.com/apache/rocketmq-client-go
方式 2）服务端部署 broker + proxy模式，让服务侧支持 grpc协议；

**Comment by zkcrescent** [comment]
`docker run -d --name rocketmq-broker-a --network rocketmq -p 10909:10909 -p 10911:10911 -v /Users/wangbailu/docker/rocketmq/broker/broker-a/logs:/root/logs -v /Users/wangbailu/docker/rocketmq/broker/broker-a/conf:/home/rocketmq/rocketmq-5.1.4/conf apache/rocketmq:5.1.4 sh mqbroker --enable-proxy -c /home/rocketmq/rocketmq-5.1.4/conf/broker.conf` 修改启动命令重新启动 broker 的容器报错
![image](https://github.com/apache/rocketmq-clients/assets/14883259/ff7fdd8b-f294-491e-8c84-d6a5b077bdfe)
去掉 --enable-proxy 就可以跑起来。

**Comment by zkcrescent** [comment]
还需要加-n `namersrv:prot` 参数。已经修改了且rocketmq已经正常启动，也显示了proxy启动成功的提示 
![image](https://github.com/apache/rocketmq-clients/assets/14883259/983dfca2-cf01-4ff8-852b-82ebc0127fd9)
用  https://github.com/apache/rocketmq-clients/blob/master/golang/example/producer/async/main.go example 代码依然不能连上

**Comment by zkcrescent** [comment]
从页面上看到 topic 的路由信息是到`172.19.0.3` 对应到容器内broker地址，怀疑是到broker链接不上， 启动一个centos 容器挂载到同一个network 下运行相关代码，修改endpoint 到 `172.19.0.2:9876` 也显示超时。

**Comment by lollipopjin** [comment]
> 将broker 的配置 `brokerIP1` 换成本机IP后，`github.com/apache/rocketmq-client-go/v2` 可以使用了，但是 `github.com/apache/rocketmq-clients/golang/v5` 还是不可以，这边已经按上述提到的启用了broker + proxy模式

可以找下客户端和服务端的日志；看下是哪里报错

**Comment by zkcrescent** [comment]
服务端没有报错信息，客户端就显示超时，没有其他信息了

**Comment by phynos** [comment]
同样问题
服务器使用broker + proxy模式部署，客户端java连接9876端口能正常连上并消费；客户端使用go（用的官方v5的样例代码）连接9876端口无法启动，连接8081端口可以正常启动并消费；
请问go客户端不支持namserver连接吗？必须使用8081端口吗？
