### ISSUE TITLE
[Enhancement] Add namespace in java client

### ISSUE THREAD

**Issue by drpmma** [apache/rocketmq-clients#660]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Programming Language of the Client

Java

### Summary

Add namespace in java client.

### Motivation

For the purpose for the future namespace feature.

### Describe the Solution You'd Like

Add namespace in ClientConfiguration.

### Describe Alternatives You've Considered

No

**Comment by lizhanhui** [comment]
What is the purpose of "For the purpose for the future namespace feature"?
Are you guys planning to add multi-tenant support to proxy/gateway? 
What is the plan for other bindings out there?
@drpmma

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `type/enhancement` | Status: **Evaluated**

Thank you for this enhancement suggestion. This has been noted for community discussion.

If you'd like to contribute a fix, feel free to submit a PR. The maintainers will review and provide feedback.

---
*Automated evaluation by RockteMQ-AI*
