### ISSUE TITLE
Thing message review failed

### ISSUE THREAD

**Issue by zhaohai666** [apache/rocketmq-clients#675]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

Node.js

### Runtime Platform Environment

mac

### RocketMQ Version of the Client/Server

test version

### Describe the Bug

TypeError: Cannot read properties of undefined (reading 'COMMIT')

### Steps to Reproduce

const producer = new Producer({
        endpoints: "127.0.0.1:8080",
        maxAttempts: 2,
        checker: {
            async check(messageView) {
                console.log("messageView : ", messageView);
                return TransactionResolution.COMMIT;
            },
        },
    });
    await producer.startup();
    const transaction = producer.beginTransaction();
    const tag = "transaction";
    const receipt = await producer.send({
        topic: topic.transaction,
        tag,
        keys: [
            `foo-key-${Date.now()}`,
            `bar-key-${Date.now()}`,
        ],
        body: Buffer.from(JSON.stringify({
            hello: 'rocketmq-client-nodejs world 😄',
            now: Date(),
        })),
    }, transaction);
    await transaction.commit();

### What Did You Expect to See?

Submit transaction review

### What Did You See Instead?

Submit transaction review failed

**Comment by RongtongJin** [comment]
@fengmk2

**Comment by fengmk2** [comment]
please assign to me
