### ISSUE TITLE
[Feature] Is python client development going well?

### ISSUE THREAD

**Issue by ma-pony** [apache/rocketmq-clients#678]
### Programming Language of the Client

Python

### Is Your Feature Request Related to a Problem?

I've noticed that rockertmq-clients/python code hasn't been updated in 5 months, is development still going well and is there anything i can do help.  I'm planning to use rocketmq in a python project.

### Describe the Solution You'd Like

null

### Describe Alternatives You've Considered

null

**Comment by lizhanhui** [comment]
To my knowledge, it's still at the alpha stage.
