### ISSUE TITLE
[DISCUSS] C++ client refuses to start on receipt of incomplete Settings response

### ISSUE THREAD

**Issue by lizhimins** [apache/rocketmq-clients#700]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).
- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.
- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

C++

### Runtime Platform Environment

CentOS8

### RocketMQ Version of the Client/Server

RocketMQ C++ client 5.0.1 and Master branch of C++ version (2024.3.11)

### Run or Compiler Version

g++ (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)

### Describe the Bug

[Bug] C++ client fails to start due to incorrect configuration sync. Client print log "Unknown metric address scheme"

### Steps to Reproduce

When client start, receive setting from server.
![image](https://github.com/apache/rocketmq-clients/assets/22487634/3c7ebdf0-0bb0-4093-b001-90c838019f3b)

C++ Client
![image](https://github.com/apache/rocketmq-clients/assets/22487634/9f2fe40e-efa0-4ba4-b3f5-45b3e58ec74d)

Java Client
![image](https://github.com/apache/rocketmq-clients/assets/22487634/1457899a-db88-4908-90fc-b40df8f111c9)

### What Did You Expect to See?

Client init success

### What Did You See Instead?

Client print error log "Unknown metric address scheme".

![image](https://github.com/apache/rocketmq-clients/assets/22487634/7f924857-93b1-4716-ba03-3ff7acaeac7f)

**Comment by lizhanhui** [comment]
The observation is caused by a defect by the proxy server. It generates setting responses that do not include required scheme type in the metric endpoint.

**Comment by lizhanhui** [comment]
![image](https://github.com/apache/rocketmq-clients/assets/641819/1acd8a51-11be-4920-9607-6d1828297f60)

after logging out the response endpoint in debug-string, you can see the following

![image](https://github.com/apache/rocketmq-clients/assets/641819/029a9b9b-e7ea-4e98-96d8-26ad58633f42)

**Comment by lizhimins** [comment]
There are two points here: 
1. Maintaining consistent behavior with Java clients
2. Maintaining compatibility if the rocketmq server is not updated

**Comment by lizhanhui** [comment]
> There are two points here:
> 
> 1. Maintaining consistent behavior with Java clients
> 2. Maintaining compatibility if the rocketmq server is not updated

For 1, Java impl does not check  as thoroughly as possible; for 2, it's not reasonable enough to relax checks in C++ Impl; C++ does not offer a safe world by default, we need check things are right as thoroughly as possible; Otherwise, the project would soon be too hard to maintain.

In either case, it's not a bug in the C++ SDK, right?

**Comment by 0902horn** [comment]
> > There are two points here:
> > 
> > 1. Maintaining consistent behavior with Java clients
> > 2. Maintaining compatibility if the rocketmq server is not updated
> 
> For 1, Java impl does not check as thoroughly as possible; for 2, it's not reasonable enough to relax checks in C++ Impl; C++ does not offer a safe world by default, we need check things are right as thoroughly as possible; Otherwise, the project would soon be too hard to maintain.
> 
> In either case, it's not a bug in the C++ SDK, right?

I thinks it is more about SDK consistency across different languages. We could fix it like this if you have security concern  about "default" in C++. 

```
    case rmq::AddressScheme::ADDRESS_SCHEME_UNSPECIFIED:
    case rmq::AddressScheme::DOMAIN_NAME: {
      service_endpoint.append("dns:");
      break;
    }
    default: {
      SPDLOG_ERROR("Unknown metric address scheme");
    }
```

According to https://github.com/apache/rocketmq/issues/7896, this can be seen as a legacy issue and should be taken care of on SDK side. In fact, Java SDK works by dealing with this case in "default" statement, and so does C# version. So if C++ SDK doesn't work like this, it should be seen as a bug.

**Comment by lizhanhui** [comment]
> I thinks it is more about SDK consistency across different languages. We could fix it like this if you have security concern about "default" in C++.

> According to https://github.com/apache/rocketmq/issues/7896, this can be seen as a legacy issue and should be taken care of on SDK side. In fact, Java SDK works by dealing with this case in "default" statement, and so does C# version. So if C++ SDK doesn't work like this, it should be seen as a bug.

No. You guys are going to the opposite way. Java and C# DOES NOT CHECK THE REQUIRED FIELD AT ALL. it's not the C++ impl buggy, instead, we need to file pull request to consolidate impls so that they comply with the protocol defined in the [protocol](https://github.com/apache/rocketmq-apis/blob/70eb1effd4b415678fc7214cedd3a289b0f926b9/apache/rocketmq/v2/definition.proto#L107)

BTW, there are numerous places where `Endpoints` are used and required fields are checked, are you guys planning to remove all these checks to maintain so-called consistency???

**Comment by lizhanhui** [comment]
Invalid Bug Report.
