### ISSUE TITLE
[Bug] cpp客户端(grpc)，测试发送延时消息coredump

### ISSUE THREAD

**Issue by 41405465** [apache/rocketmq-clients#705]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

C++

### Runtime Platform Environment

Red Hat Enterprise Linux Server release 7.9 (Maipo)

### RocketMQ Version of the Client/Server

5.0版本cpp客户端

### Run or Compiler Version

centos 7.9

### Describe the Bug

程序coredump，输出如下
![image](https://github.com/apache/rocketmq-clients/assets/24800419/3e6c60f0-42d3-4e61-ae1c-b0161e22383b)

### Steps to Reproduce

开启客户端，持续发送延时消息

### What Did You Expect to See?

无

### What Did You See Instead?

无

### Additional Context

#0  0x00007f6ad64fa387 in raise () from TestRocketMQModule-runtime/libs/libc.so.6
#1  0x00007f6ad64fba78 in abort () from TestRocketMQModule-runtime/libs/libc.so.6
#2  0x00007f6ad7026a95 in __gnu_cxx::__verbose_terminate_handler() () from TestRocketMQModule-runtime/libs/libstdc++.so.6
#3  0x00007f6ad7024a06 in ?? () from TestRocketMQModule-runtime/libs/libstdc++.so.6
#4  0x00007f6ad7024a33 in std::terminate() () from TestRocketMQModule-runtime/libs/libstdc++.so.6
#5  0x00007f6ad702559f in __cxa_pure_virtual () from TestRocketMQModule-runtime/libs/libstdc++.so.6
#6  0x00007f6ab9fd3e37 in grpc::ClientBidiReactor<apache::rocketmq::v2::TelemetryCommand, apache::rocketmq::v2::TelemetryCommand>::StartWrite(apache::rocketmq::v2::TelemetryCommand const*, grpc::WriteOptions) ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
#7  0x00007f6ab9fd288f in grpc::ClientBidiReactor<apache::rocketmq::v2::TelemetryCommand, apache::rocketmq::v2::TelemetryCommand>::StartWrite(apache::rocketmq::v2::TelemetryCommand const*) () from TestRocketMQModule-runtime/libs/librocketmq.so
#8  0x00007f6ab9fd08ee in rocketmq::TelemetryBidiReactor::fireWrite() () from TestRocketMQModule-runtime/libs/librocketmq.so
#9  0x00007f6ab9fd04fd in rocketmq::TelemetryBidiReactor::write(apache::rocketmq::v2::TelemetryCommand) ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
#10 0x00007f6ab9fcb939 in rocketmq::SessionImpl::syncSettings() () from TestRocketMQModule-runtime/libs/librocketmq.so
#11 0x00007f6ab9ffc3b5 in rocketmq::ClientImpl::syncClientSettings() () from TestRocketMQModule-runtime/libs/librocketmq.so
#12 0x00007f6ab9ff9d3c in rocketmq::ClientImpl::start()::{lambda()#3}::operator()() const ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
#13 0x00007f6ab9fff71c in std::_Function_handler<void (), rocketmq::ClientImpl::start()::{lambda()#3}>::_M_invoke(std::_Any_data const&) () from TestRocketMQModule-runtime/libs/librocketmq.so
#14 0x00007f6ab9ef627a in std::function<void ()>::operator()() const () from TestRocketMQModule-runtime/libs/librocketmq.so
#15 0x00007f6aba0780a4 in rocketmq::SchedulerImpl::execute(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>) ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
#16 0x00007f6aba08a17b in void std::__invoke_impl<void, void (*&)(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>), std::error_code const&, std::weak_ptr<rocketmq::TimerTask>&>(std::__invoke_other, void (*&)(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>), std::error_code const&, std::weak_ptr<rocketmq::TimerTask>&) ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
#17 0x00007f6aba0896ed in std::__invoke_result<void (*&)(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>), std::error_code const&, std::weak_ptr<rocketmq::TimerTask>&>::type std::__invoke<void (*&)(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>), std::error_code const&, std::weak_ptr<rocketmq::TimerTask>&>(void (*&)(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>), std::error_code const&, std::weak_ptr<rocketmq::TimerTask>&) ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
#18 0x00007f6aba088965 in void std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>::__call<void, std::error_code const&, 0ul, 1ul>(std::tuple<std::error_code const&>&&, std::_Index_tuple<0ul, 1ul>) () from TestRocketMQModule-runtime/libs/librocketmq.so
#19 0x00007f6aba0873ab in void std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>::operator()<std::error_code const&, void>(std::error_code const&) ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
#20 0x00007f6aba086083 in asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(st---Type <return> to continue, or q <return> to quit---
d::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code>::operator()() ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
#21 0x00007f6aba08539c in void asio::asio_handler_invoke<asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code> >(asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code>&, ...) () from TestRocketMQModule-runtime/libs/librocketmq.so
#22 0x00007f6aba0841ce in void asio_handler_invoke_helpers::invoke<asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code>, std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)> >(asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code>&, std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>&) () from TestRocketMQModule-runtime/libs/librocketmq.so
#23 0x00007f6aba0825a8 in void asio::detail::handler_work<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, asio::any_io_executor, void>::complete<asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code> >(asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code>&, std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>&) ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
#24 0x00007f6aba081511 in asio::detail::wait_handler<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, asio::any_io_executor>::do_complete(void*, asio::detail::scheduler_operation*, std::error_code const&, unsigned long) () from TestRocketMQModule-runtime/libs/librocketmq.so
#25 0x00007f6ab9f7c636 in asio::detail::scheduler_operation::complete(void*, std::error_code const&, unsigned long) ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
#26 0x00007f6ab9f7e645 in asio::detail::scheduler::do_run_one(asio::detail::conditionally_enabled_mutex::scoped_lock&, asio::detail::scheduler_thread_info&, std::error_code const&) () from TestRocketMQModule-runtime/libs/librocketmq.so
#27 0x00007f6ab9f7e243 in asio::detail::scheduler::run(std::error_code&) () from TestRocketMQModule-runtime/libs/librocketmq.so
#28 0x00007f6ab9f7e957 in asio::io_context::run(std::error_code&) () from TestRocketMQModule-runtime/libs/librocketmq.so
#29 0x00007f6aba07750d in rocketmq::SchedulerImpl::start()::{lambda()#1}::operator()() const ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
#30 0x00007f6aba078699 in void std::__invoke_impl<void, rocketmq::SchedulerImpl::start()::{lambda()#1}>(std::__invoke_other, rocketmq::SchedulerImpl::start()::{lambda()#1}&&) () from TestRocketMQModule-runtime/libs/librocketmq.so
#31 0x00007f6aba0784cf in std::__invoke_result<rocketmq::SchedulerImpl::start()::{lambda()#1}>::type std::__invoke<rocketmq::SchedulerImpl::start()::{lambda()#1}>(std::__invoke_result&&, (rocketmq::SchedulerImpl::start()::{lambda()#1}&&)...) ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
#32 0x00007f6aba078b10 in decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<rocketmq::SchedulerImpl::start()::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) () from TestRocketMQModule-runtime/libs/librocketmq.so
#33 0x00007f6aba078ae1 in std::thread::_Invoker<std::tuple<rocketmq::SchedulerImpl::start()::{lambda()#1}> >::operator()() ()
   from TestRocketMQModule-runtime/libs/librocketmq.so
---Type <return> to continue, or q <return> to quit---
#34 0x00007f6aba078ac0 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<rocketmq::SchedulerImpl::start()::{lambda()#1}> > >::_M_run() () from TestRocketMQModule-runtime/libs/librocketmq.so
#35 0x00007f6abaa3f5df in execute_native_thread_routine () from TestRocketMQModule-runtime/libs/librocketmq.so
#36 0x00007f6ad6899ea5 in start_thread () from TestRocketMQModule-runtime/libs/libpthread.so.0
#37 0x00007f6ad65c2b0d in clone () from TestRocketMQModule-runtime/libs/libc.so.6

**Comment by lizhanhui** [comment]
Thanks for the bug report. I will look into it

**Comment by lizhanhui** [comment]
@41405465 This commit should fix this issue: https://github.com/lizhanhui/rocketmq-clients/commit/185a812a6b18ee777de7f78feb8111187e6d07de

You can help verify and preview the change.

**Comment by lizhanhui** [comment]
fixed [here](https://github.com/apache/rocketmq-clients/tree/develop-cpp)
