### ISSUE TITLE
库贡献者们，rocketmq-client-nodejs是真的有测试通过后发布的吗

### ISSUE THREAD

**Issue by Luwei199169** [apache/rocketmq-clients#723]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

Node.js

### Runtime Platform Environment

Windows 10

### RocketMQ Version of the Client/Server

rocketmq-client-nodejs

### Run or Compiler Version

Node.js v18.19.1

### Describe the Bug

库贡献者们，rocketmq-client-nodejs是真的有测试通过后发布的吗

### Steps to Reproduce

库贡献者们，rocketmq-client-nodejs是真的有测试通过后发布的吗

### What Did You Expect to See?

库贡献者们，rocketmq-client-nodejs是真的有测试通过后发布的吗

### What Did You See Instead?

库贡献者们，rocketmq-client-nodejs是真的有测试通过后发布的吗

### Additional Context

库贡献者们，rocketmq-client-nodejs是真的有测试通过后发布的吗

**Comment by 41405465** [comment]
我感觉是完全没有测试过，很基础的问题存在，想直接用起来根本不可能，可能他们只想支持java。
倒是我在测试，发现问题再提给他们，但是解不解决也是看他们心情。
我用的是cpp版本。

**Comment by ifplusor** [comment]
使用的server是什么版本，client是否可以切到 https://github.com/apache/rocketmq-clients/tree/master/nodejs 呢？

**Comment by drpmma** [comment]
This issue is not related to this repository, please submit issue in the corresponding [repository](https://github.com/apache/rocketmq-client-nodejs).

**Comment by lizhanhui** [comment]
> 我感觉是完全没有测试过，很基础的问题存在，想直接用起来根本不可能，可能他们只想支持java。 倒是我在测试，发现问题再提给他们，但是解不解决也是看他们心情。 我用的是cpp版本。

1. 代码, 测试代码都在仓库里面, 不需要"我感觉是完全没有测试过";
2. "很基础的问题存在，想直接用起来根本不可能", 这份代码在[钉钉](http://www.52im.net/thread-4106-1-1.html)运行三年多了, 也有一些别的企业在生产上使用. 
3. "可能他们只想支持java" 你对社区的基本发展方向缺乏基本的了解.
4.  "倒是我在测试，发现问题再提给他们，但是解不解决也是看他们心情" 你只是提了个疑似点, 是否是bug还需要进一步确认; Apache社区是开发者, 维护者, 用户一起构建的, 没有"他们"; 所有参与者都是用爱发电, 所以问题修复, 版本迭代节奏比企业内部要慢很多; 您没有花钱购买付费服务, 还请你有个理性的认知.
