### ISSUE TITLE
[Enhancement] ClientConfiguration Add namespace

### ISSUE THREAD

**Issue by zhaohai666** [apache/rocketmq-clients#746]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Programming Language of the Client

Node.js

### Summary

The Java language already supports this namespace configuration addition, and I hope node js will also support it.

### Motivation

The Java language already supports this namespace configuration addition, and I hope node js will also support it.

### Describe the Solution You'd Like

ClientConfiguration Add namespace

### Describe Alternatives You've Considered

ClientConfiguration Add namespace

**Comment by fengmk2** [comment]
It is possible to do so, and at the same time, direct contributions are welcome.

**Comment by zhaohai666** [comment]
#750
