### ISSUE TITLE
Producer is not running now  消息发送以后再发送消息就报这个错，把producer.close(); 去了就不报错

### ISSUE THREAD

**Issue by pzx6b666** [apache/rocketmq-clients#764]
### Programming Language of the Client

Java

### Is Your Feature Request Related to a Problem?

    final ClientServiceProvider provider = ClientServiceProvider.loadService();

        String topic = "yourNormalTopic";
        final Producer producer = ProducerSingleton.getInstance(topic);
  
        byte[] body = "This is a normal message for Apache RocketMQ".getBytes(StandardCharsets.UTF_8);
        String tag = "yourMessageTagA";
        final Message message = provider.newMessageBuilder()
            .setTopic(topic)
            .setTag(tag)
            .setKeys("yourMessageKey-1c151062f96e")
            .setBody(body)
            .build();
        try {
            final SendReceipt sendReceipt = producer.send(message);
            log.info("Send message successfully, messageId={}", sendReceipt.getMessageId());
        } catch (Throwable t) {
            log.error("Failed to send message", t);
        }
     
producer.close();

### Describe the Solution You'd Like

1

### Describe Alternatives You've Considered

1

### Additional Context

1

**Comment by JanYork** [comment]
本来就是这样的，你都关闭生产者了，他肯定报错呀

**Comment by pzx6b666** [comment]
> 本来就是这样的，你都关闭生产者了，他肯定报错呀


第一次调用发送完消息以后执行close，再次调用不应该重新初始化吗
sendmsg(){

final ClientServiceProvider provider = ClientServiceProvider.loadService();

    String topic = "yourNormalTopic";
    final Producer producer = ProducerSingleton.getInstance(topic);

    byte[] body = "This is a normal message for Apache RocketMQ".getBytes(StandardCharsets.UTF_8);
    String tag = "yourMessageTagA";
    final Message message = provider.newMessageBuilder()
        .setTopic(topic)
        .setTag(tag)
        .setKeys("yourMessageKey-1c151062f96e")
        .setBody(body)
        .build();
    try {
        final SendReceipt sendReceipt = producer.send(message);
        log.info("Send message successfully, messageId={}", sendReceipt.getMessageId());
    } catch (Throwable t) {
        log.error("Failed to send message", t);
    }finally{
producer.close()
}

}
