### ISSUE TITLE
[NodeJS发送消息速度好慢

### ISSUE THREAD

**Issue by Gufang666** [apache/rocketmq-clients#828]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Programming Language of the Client

Node.js

### Summary

测试单节点for循环进行消息发送，每秒只能发送700条左右

### Motivation

测试单节点for循环进行消息发送，每秒只能发送700条左右

### Describe the Solution You'd Like

测试单节点for循环进行消息发送，每秒只能发送700条左右

### Describe Alternatives You've Considered

测试单节点for循环进行消息发送，每秒只能发送700条左右

### Additional Context

测试单节点for循环进行消息发送，每秒只能发送700条左右

**Comment by JanYork** [comment]
Perhaps you could try putting the consumer and producer into a node.js worker to avoid the latency caused by the single-threaded event loop.
I'm not sure if the latency is caused by having too many queues in the event loop, but you could try it.

**Comment by Gufang666** [comment]
I only tested the message sending rate by performing a loop-based message sending test. Both the C++ and Java clients achieved about 2000 messages per second, but the rate for the Node.js client is significantly lower. I'm not sure if there's an issue with the testing method.
