### ISSUE TITLE
当我一个group下需要订阅多个topic，api好像是不支持的

### ISSUE THREAD

**Issue by zengwenhao12** [apache/rocketmq-clients#830]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Programming Language of the Client

Java

### Summary

当我一个group下需要订阅多个topic，api好像是不支持的

### Motivation

当我一个group下需要订阅多个topic，api好像是不支持的

### Describe the Solution You'd Like

当我一个group下需要订阅多个topic，api好像是不支持的

### Describe Alternatives You've Considered

当我一个group下需要订阅多个topic，api好像是不支持的

### Additional Context

当我一个group下需要订阅多个topic，api好像是不支持的

**Comment by JanYork** [comment]
Maybe it shouldn't be like that, group is an abstraction of the isolated situation of topic, and topic is the largest level of business classification, according to your needs, I think it's more important to change this one group need to subscribe to multiple topics to one topic corresponding to multiple groups and different subscription rules or tags of consumers in the group.
