### ISSUE TITLE
[Bug] consumeMessageConcurrently panic

### ISSUE THREAD

**Issue by lyp9624** [apache/rocketmq-clients#848]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

Go

### Runtime Platform Environment

ubuntu 20.04

### RocketMQ Version of the Client/Server

client version rocketmq-client-go/v2 v2.1.2

### Describe the Bug

client just get these error messages, these made client cannot consume the message:
time="2024-10-18T10:02:44Z" level=error msg="consumeMessageConcurrently panic" consumerGroup=higgs_boss_billing_usage_consumer underlayError="decimal division by 0"

time="2024-10-18T09:58:04Z" level=error msg="consumeMessageConcurrently panic" consumerGroup=sensetime-core-boss-billing-hourly-consumer underlayError="runtime error: invalid memory address or nil pointer dereference"

### Steps to Reproduce

have no idea

### What Did You Expect to See?

how to get rid of these error

### What Did You See Instead?

no idea

**Comment by GwenLily** [comment]
hello, I had this problem too, how was it resolved

**Comment by orcswang-lang** [comment]
> hello, I had this problem too, how was it resolved你好，我也遇到了这个问题，请问后来怎么解决的
需要强制设置一个Credentials，其中AccessKey、AccessSecret为空
