### ISSUE TITLE
[Feature] Producer send message do not support  batch send

### ISSUE THREAD

**Issue by xieyj-apple** [apache/rocketmq-clients#886]
### Programming Language of the Client

Go

### Is Your Feature Request Related to a Problem?

producer接口都只支持单条发送消息吗，为什么不支持批量
type Producer interface {
	Send(context.Context, *Message) ([]*SendReceipt, error)
	SendWithTransaction(context.Context, *Message, Transaction) ([]*SendReceipt, error)
	SendAsync(context.Context, *Message, func(context.Context, []*SendReceipt, error))
	BeginTransaction() Transaction
	Start() error
	GracefulStop() error
	isClient
}

### Describe the Solution You'd Like

支持批量

### Describe Alternatives You've Considered

支持批量

**Comment by qianye1001** [comment]
5.x client need 5.x proxy, proxy do not support batch send now

**Comment by lizhimins** [comment]
protocol not support now
