### ISSUE TITLE
[Feature] 5.x Client can support  4.x rocketmq server?

### ISSUE THREAD

**Issue by xieyj-apple** [apache/rocketmq-clients#887]
### Programming Language of the Client

Go

### Is Your Feature Request Related to a Problem?

i use 5.x Client to connect with 4.x rocketmq namesrv address， i found that it return  "create grpc conn failed"

### Describe the Solution You'd Like

client support lower rocketmq

### Describe Alternatives You've Considered

client support lower rocketmq

**Comment by qianye1001** [comment]
5.x Client need 5.x proxy, can not connect namesrv

**Comment by lizhimins** [comment]
5.x client based on gRPC protocol，client connect to proxy rather than ns or broker
